[phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["mkdir -p database website data"]

[start]
cmd = "node server/index.js & node scheduler.js & wait"
